using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace GONES.Model.Pg;

/// <summary>
/// [2026-09-23] snake_case 列/表名约定。PG 库已全量改名为 snake_case（rename_to_snake_case.sql）。
/// 在 OnModelCreating 末尾统一把每个实体属性映射到 snake_case 列名、把表名改成 snake_case，
/// 使 EF 解析与已改名的 PG 库一致；C# 属性名保持 PascalCase 不变。
/// 列映射直接烘焙自 temp/column_rename_locked.json（与 DB 改名同源，权威），不依赖运行时 snake 算法。
/// </summary>
public static class SnakeCaseConvention
{
        private static readonly Dictionary<string,string> TableMap = new(StringComparer.OrdinalIgnoreCase)
        {
            { "t_ERP_DataDict", "t_erp_data_dict" },
            { "t_ERP_Department", "t_erp_department" },
            { "t_ERP_ITEM", "t_erp_item" },
            { "t_ERP_ITEMCLASS", "t_erp_itemclass" },
            { "t_ERP_ITEMGROUP", "t_erp_itemgroup" },
            { "t_ERP_Menu", "t_erp_menu" },
            { "t_ERP_Role", "t_erp_role" },
            { "t_ERP_RoleMenu", "t_erp_role_menu" },
            { "t_ERP_ShopInfo", "t_erp_shop_info" },
            { "t_ERP_UserInfo", "t_erp_user_info" },
            { "t_PMS_BatchNoStock", "t_pms_batch_no_stock" },
            { "t_PMS_BillUse", "t_pms_bill_use" },
            { "t_PMS_BillUseEntry", "t_pms_bill_use_entry" },
            { "t_PMS_DefaultPickerInfo", "t_pms_default_picker_info" },
            { "t_PMS_GoodsApply", "t_pms_goods_apply" },
            { "t_PMS_GoodsApplyEntry", "t_pms_goods_apply_entry" },
            { "t_PMS_ProduceOrder", "t_pms_produce_order" },
            { "t_PMS_ProduceOrderProductEntry", "t_pms_produce_order_product_entry" },
            { "t_PMS_ProduceOrderRawMaterialEntry", "t_pms_produce_order_raw_material_entry" },
            { "t_PMS_ProduceOrderStepEntry", "t_pms_produce_order_step_entry" },
            { "t_PMS_Step", "t_pms_step" },
            { "t_PMS_StepProductBom", "t_pms_step_product_bom" },
            { "t_PMS_StockBill", "t_pms_stock_bill" },
            { "t_PMS_StockBillEntry", "t_pms_stock_bill_entry" },
            { "t_PMS_Worker", "t_pms_worker" },
        };

        private static readonly Dictionary<string, Dictionary<string,string>> ColMap = new(StringComparer.OrdinalIgnoreCase)
        {
            { "t_ERP_DataDict", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "DictName", "dict_name" },
                { "DictNo", "dict_no" },
                { "FParentID", "f_parent_id" },
                { "ID", "id" },
                { "IsShow", "is_show" },
                { "Remark", "remark" },
            } },
            { "t_ERP_Department", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "DEPLevel", "dep_level" },
                { "DEPName", "dep_name" },
                { "ID", "id" },
                { "IsDEP", "is_dep" },
                { "ParentID", "parent_id" },
                { "Status", "status" },
            } },
            { "t_ERP_ITEM", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "ID", "id" },
            } },
            { "t_ERP_ITEMCLASS", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "ClassLevel", "class_level" },
                { "FParentID", "f_parent_id" },
                { "ID", "id" },
            } },
            { "t_ERP_ITEMGROUP", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "ID", "id" },
                { "ComponentItemGuid", "component_item_guid" },
                { "ComponentItemCode", "component_item_code" },
                { "ComboItemGuid", "combo_item_guid" },
                { "ComboItemCode", "combo_item_code" },
                { "BaseQuantity", "base_quantity" },
                { "UnitPrice", "unit_price" },
                { "DepartmentId", "department_id" },
                { "IsRepairStatus", "is_repair_status" },
            } },
            { "t_ERP_Menu", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "ClassName", "class_name" },
                { "DllName", "dll_name" },
                { "Flag", "flag" },
                { "ID", "id" },
                { "Memo", "memo" },
                { "MenuName", "menu_name" },
                { "Route", "route" },
                { "MenuType", "menu_type" },
                { "OpenType", "open_type" },
                { "Operating", "operating" },
                { "ParentID", "parent_id" },
            } },
            { "t_ERP_Role", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "ID", "id" },
                { "Iselect", "iselect" },
                { "IsReadonly", "is_readonly" },
                { "RoleMemo", "role_memo" },
                { "RoleName", "role_name" },
            } },
            { "t_ERP_RoleMenu", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "ID", "id" },
                { "MenuID", "menu_id" },
                { "RoleID", "role_id" },
            } },
            { "t_ERP_ShopInfo", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "Address", "address" },
                { "AppSecrect", "app_secret" },
                { "Appkey", "appkey" },
                { "ConfigData", "config_data" },
                { "ID", "id" },
                { "IsAgent", "is_agent" },
                { "IsAutoDown", "is_auto_down" },
                { "IsEnable", "is_enable" },
                { "IsHandMerge", "is_hand_merge" },
                { "IsImport", "is_import" },
                { "IsMerge", "is_merge" },
                { "IsMessage", "is_message" },
                { "IsRFM", "is_rfm" },
                { "Message", "message" },
                { "OrderCount", "order_count" },
                { "Phone", "phone" },
                { "QQ", "qq" },
                { "SendAisle", "send_aisle" },
                { "SessionEndDate", "session_end_date" },
                { "SessionKey", "session_key" },
                { "ShopName", "shop_name" },
                { "ShopNumber", "shop_number" },
                { "ShopSort", "shop_sort" },
                { "ShopType", "shop_type" },
            } },
            { "t_ERP_UserInfo", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "Account", "account" },
                { "DEPID", "dep_id" },
                { "Depot", "depot" },
                { "ID", "id" },
                { "IsLogin", "is_login" },
                { "MacAddress", "mac_address" },
                { "PassWord", "password" },
                { "PwdMustChange", "pwd_must_change" },
                { "RoleID", "role_id" },
                { "Shop", "shop" },
                { "Status", "status" },
                { "UserName", "user_name" },
            } },
            { "t_PMS_BatchNoStock", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "FBatchNo", "f_batch_no" },
                { "FBatchNum", "f_batch_num" },
                { "FBegDate", "f_beg_date" },
                { "FBillType", "f_bill_type" },
                { "FEndDate", "f_end_date" },
                { "FInterID", "f_inter_id" },
                { "FItemID", "f_item_id" },
                { "FName", "f_name" },
                { "FPrice", "f_price" },
                { "FState", "f_state" },
            } },
            { "t_PMS_BillUse", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "FBillNo", "f_bill_no" },
                { "FBillType", "f_bill_type" },
                { "FCreaterID", "f_creater_id" },
                { "FDate", "f_date" },
                { "FDeptID", "f_dept_id" },
                { "FGroupID", "f_group_id" },
                { "FInterID", "f_inter_id" },
                { "FRemark", "f_remark" },
                { "FWorkPeople", "f_work_people" },
                { "FWorkShopID", "f_work_shop_id" },
                { "FWorkerID", "f_worker_id" },
            } },
            { "t_PMS_BillUseEntry", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "FBomId", "f_bom_id" },
                { "FCurrentUseNum", "f_current_use_num" },
                { "FEntryID", "f_entry_id" },
                { "FInterID", "f_inter_id" },
                { "FIsProduct", "f_is_product" },
                { "FIsUse", "f_is_use" },
                { "FItemID", "f_item_id" },
                { "FLastUseNum", "f_last_use_num" },
                { "FProduceId", "f_produce_id" },
                { "FProduceNo", "f_produce_no" },
                { "FScheduleNo", "f_schedule_no" },
                { "FScheduleNoID", "f_schedule_no_id" },
                { "FStepID", "f_step_id" },
                { "FUseNum", "f_use_num" },
            } },
            { "t_PMS_DefaultPickerInfo", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "FBomID", "f_bom_id" },
                { "FDeptID", "f_dept_id" },
                { "FGroupID", "f_group_id" },
                { "FID", "id" },
                { "FWorkShopID", "f_work_shop_id" },
                { "FWorkerID", "f_worker_id" },
            } },
            { "t_PMS_GoodsApply", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "FBillNo", "f_bill_no" },
                { "FBillerID", "f_biller_id" },
                { "FCancellation", "f_cancellation" },
                { "FCheckDate", "f_check_date" },
                { "FCheckerID", "f_checker_id" },
                { "FDate", "f_date" },
                { "FDeptID", "f_dept_id" },
                { "FEmpID", "f_emp_id" },
                { "FExplanation", "f_explanation" },
                { "FFetchAdd", "f_fetch_add" },
                { "FInterID", "f_inter_id" },
                { "FModifyDate", "f_modify_date" },
                { "FModifyerID", "f_modifyer_id" },
                { "FStatus", "f_status" },
                { "FStockID", "f_stock_id" },
                { "FTranType", "f_tran_type" },
                { "FUserID", "f_user_id" },
                { "FWorkShopID", "f_work_shop_id" },
            } },
            { "t_PMS_GoodsApplyEntry", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "FAmount", "f_amount" },
                { "FBomId", "f_bom_id" },
                { "FEntryID", "f_entry_id" },
                { "FFetchDate", "f_fetch_date" },
                { "FFetchNum", "f_fetch_num" },
                { "FInterID", "f_inter_id" },
                { "FItemID", "f_item_id" },
                { "FNote", "f_note" },
                { "FPrice", "f_price" },
                { "FQty", "f_qty" },
                { "FSecCoefficient", "f_sec_coefficient" },
                { "FSecQty", "f_sec_qty" },
                { "FStatus", "f_status" },
                { "FStockID", "f_stock_id" },
                { "FUnitID", "f_unit_id" },
            } },
            { "t_PMS_ProduceOrder", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "FApplyDate", "f_apply_date" },
                { "FApplyNo", "f_apply_no" },
                { "FApplyerID", "f_applyer_id" },
                { "FAuditDate", "f_audit_date" },
                { "FAuditorID", "f_auditor_id" },
                { "FBillNo", "f_bill_no" },
                { "FComment", "f_comment" },
                { "FCreaterID", "f_creater_id" },
                { "FDate", "f_date" },
                { "FDeptID", "f_dept_id" },
                { "FInterID", "f_inter_id" },
                { "FModifyDate", "f_modify_date" },
                { "FModifyerID", "f_modifyer_id" },
                { "FOrderStatus", "f_order_status" },
                { "FPickNo", "f_pick_no" },
                { "FRemark", "f_remark" },
                { "FScheduleNo", "f_schedule_no" },
                { "FScheduleNoID", "f_schedule_no_id" },
                { "FStatus", "f_status" },
                { "FWorkShopID", "f_work_shop_id" },
            } },
            { "t_PMS_ProduceOrderProductEntry", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "FBatchNumber", "f_batch_number" },
                { "FBillApplyEntryID", "f_bill_apply_entry_id" },
                { "FBillApplyInterID", "f_bill_apply_inter_id" },
                { "FBillUseFInterID", "f_bill_use_f_inter_id" },
                { "FBomId", "f_bom_id" },
                { "FEntryID", "f_entry_id" },
                { "FInterID", "f_inter_id" },
                { "FItemID", "f_item_id" },
                { "FOutAmount", "f_out_amount" },
                { "FOutFactory", "f_out_factory" },
                { "FOutPrice", "f_out_price" },
                { "FPickingStatus", "f_picking_status" },
                { "FPlanDate", "f_plan_date" },
                { "FPlanNum", "f_plan_num" },
                { "FProduceType", "f_produce_type" },
                { "FProductionPickingStatus", "f_production_picking_status" },
                { "FStockStatus", "f_stock_status" },
            } },
            { "t_PMS_ProduceOrderRawMaterialEntry", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "FBomId", "f_bom_id" },
                { "FEntryID", "f_entry_id" },
                { "FFixedLoss", "f_fixed_loss" },
                { "FInterID", "f_inter_id" },
                { "FItemID", "f_item_id" },
                { "FLossRate", "f_loss_rate" },
                { "FLossStandValue", "f_loss_stand_value" },
                { "FLossUnit", "f_loss_unit" },
                { "FLossValue", "f_loss_value" },
                { "FNeedNum", "f_need_num" },
                { "FNum", "f_num" },
                { "FPriceUnit", "f_price_unit" },
                { "FRemark", "f_remark" },
                { "FStepID", "f_step_id" },
                { "FWorkHourUnit", "f_work_hour_unit" },
            } },
            { "t_PMS_ProduceOrderStepEntry", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "FAlgo", "f_algo" },
                { "FBomId", "f_bom_id" },
                { "FEntryID", "f_entry_id" },
                { "FFixedLoss", "f_fixed_loss" },
                { "FHour", "f_hour" },
                { "FHourArti", "f_hour_arti" },
                { "FInterID", "f_inter_id" },
                { "FItemID", "f_item_id" },
                { "FLossRate", "f_loss_rate" },
                { "FLossStandValue", "f_loss_stand_value" },
                { "FLossUnit", "f_loss_unit" },
                { "FLossValue", "f_loss_value" },
                { "FNum", "f_num" },
                { "FOutPutNum", "f_out_put_num" },
                { "FPlanOutPutNum", "f_plan_out_put_num" },
                { "FPrice", "f_price" },
                { "FPriceUnit", "f_price_unit" },
                { "FSingleArti", "f_single_arti" },
                { "FStepID", "f_step_id" },
                { "FWorkHourUnit", "f_work_hour_unit" },
            } },
            { "t_PMS_Step", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "FAlgo", "f_algo" },
                { "FDelete", "f_delete" },
                { "FFixedLoss", "f_fixed_loss" },
                { "FHour", "f_hour" },
                { "FHourArti", "f_hour_arti" },
                { "FItemID", "f_item_id" },
                { "FLossRate", "f_loss_rate" },
                { "FLossStandValue", "f_loss_stand_value" },
                { "FLossUnit", "f_loss_unit" },
                { "FLossValue", "f_loss_value" },
                { "FName", "f_name" },
                { "FNum", "f_num" },
                { "FPrice", "f_price" },
                { "FPriceUnit", "f_price_unit" },
                { "FSingleArti", "f_single_arti" },
                { "FType", "f_type" },
                { "FWorkHourUnit", "f_work_hour_unit" },
            } },
            { "t_PMS_StepProductBom", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "FBaseNum", "f_base_num" },
                { "FBaseUnit", "f_base_unit" },
                { "FBomID", "f_bom_id" },
                { "FCostType", "f_cost_type" },
                { "FDelete", "f_delete" },
                { "FID", "id" },
                { "FIsProduct", "f_is_product" },
                { "FLossRate", "f_loss_rate" },
                { "FLossStandValue", "f_loss_stand_value" },
                { "FLossUnit", "f_loss_unit" },
                { "FLossValue", "f_loss_value" },
                { "FPItemID", "fp_item_id" },
                { "FPrePItemID", "f_pre_p_item_id" },
                { "FPreStepID", "f_pre_step_id" },
                { "FRemark", "f_remark" },
                { "FStepId", "f_step_id" },
                { "FStepName", "f_step_name" },
            } },
            { "t_PMS_StockBill", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "FBillNo", "f_bill_no" },
                { "FBillType", "f_bill_type" },
                { "FBillTypeEx", "f_bill_type_ex" },
                { "FBuyerID", "f_buyer_id" },
                { "FBuyingUnit", "f_buying_unit" },
                { "FCreaterID", "f_creater_id" },
                { "FDate", "f_date" },
                { "FDeptID", "f_dept_id" },
                { "FGroupID", "f_group_id" },
                { "FInspectors", "f_inspectors" },
                { "FInterID", "f_inter_id" },
                { "FManagerID", "f_manager_id" },
                { "FModifyID", "f_modify_id" },
                { "FModifyTime", "f_modify_time" },
                { "FROB", "frob" },
                { "FRemark", "f_remark" },
                { "FSourceInterID", "f_source_inter_id" },
                { "FState", "f_state" },
                { "FWorkShopID", "f_work_shop_id" },
            } },
            { "t_PMS_StockBillEntry", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "FAfterTaxAmount", "f_after_tax_amount" },
                { "FAfterTaxPrice", "f_after_tax_price" },
                { "FAmount", "f_amount" },
                { "FBatchNo", "f_batch_no" },
                { "FBatchNoID", "f_batch_no_id" },
                { "FBegDate", "f_beg_date" },
                { "FBillUseEntryID", "f_bill_use_entry_id" },
                { "FBillUseNo", "f_bill_use_no" },
                { "FBomIDBatchNo", "f_bom_id_batch_no" },
                { "FBomId", "f_bom_id" },
                { "FBuyingNo", "f_buying_no" },
                { "FEndDate", "f_end_date" },
                { "FEntryID", "f_entry_id" },
                { "FInterID", "f_inter_id" },
                { "FItemID", "f_item_id" },
                { "FNote", "f_note" },
                { "FNum", "f_num" },
                { "FNumExt1", "f_num_ext1" },
                { "FNumExt2", "f_num_ext2" },
                { "FNumExt3", "f_num_ext3" },
                { "FPickBillID", "f_pick_bill_id" },
                { "FPickEntryID", "f_pick_entry_id" },
                { "FPlanDate", "f_plan_date" },
                { "FPlanNum", "f_plan_num" },
                { "FPrice", "f_price" },
                { "FProduceID", "f_produce_id" },
                { "FProduceNo", "f_produce_no" },
                { "FROB", "frob" },
                { "FSEOutNo", "fse_out_no" },
                { "FScheduleNo", "f_schedule_no" },
                { "FScheduleNoID", "f_schedule_no_id" },
                { "FStepID", "f_step_id" },
                { "FTaxAmount", "f_tax_amount" },
                { "FTaxRate", "f_tax_rate" },
                { "FTaxRateValue", "f_tax_rate_value" },
            } },
            { "t_PMS_Worker", new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)
            {
                { "DEPID", "dep_id" },
                { "FIDNumber", "fid_number" },
                { "FMobile", "f_mobile" },
                { "FName", "f_name" },
                { "ID", "id" },
                { "Status", "status" },
            } },
        };

    public static void Apply(ModelBuilder modelBuilder)
    {
        foreach (var et in modelBuilder.Model.GetEntityTypes())
        {
            if (et.ClrType == null) continue;
            var clrName = et.ClrType.Name;
            if (TableMap.TryGetValue(clrName, out var newTable)) et.SetTableName(newTable);
            if (ColMap.TryGetValue(clrName, out var cm))
            {
                foreach (var p in et.GetProperties())
                {
                    if (p.IsShadowProperty()) continue;
                    if (cm.TryGetValue(p.Name, out var nc)) p.SetColumnName(nc);
                }
            }
        }
    }
}
