--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Name: t_erp_data_dict; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_erp_data_dict (
    id integer NOT NULL,
    dict_no character varying(10),
    dict_name character varying(100),
    f_parent_id integer NOT NULL,
    remark character varying(500),
    is_show boolean DEFAULT false
);


--
-- Name: t_erp_data_dict_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_erp_data_dict ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_erp_data_dict_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_erp_department; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_erp_department (
    id integer NOT NULL,
    parent_id integer,
    dep_name text NOT NULL,
    dep_level integer NOT NULL,
    is_dep smallint NOT NULL,
    status integer NOT NULL
);


--
-- Name: t_erp_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_erp_item (
    id integer NOT NULL,
    row_guid character varying(100),
    item_code character varying(50),
    item_full_name character varying(250),
    item_short_name character varying(150),
    item_pinyin_code character varying(50),
    item_spec character varying(50),
    category_id integer,
    category_code character varying(50),
    barcode character varying(50) DEFAULT ''::character varying,
    attr1 character varying(20),
    attr2 character varying(20),
    package_unit character varying(10),
    package_rate integer,
    base_unit character varying(10),
    net_content numeric(18,3),
    total_weight numeric(18,3),
    retail_price numeric(18,2),
    factory_price numeric(18,2),
    franchise_price numeric(18,2),
    is_stock_controlled boolean,
    is_enabled boolean,
    is_combo boolean,
    is_publish_controlled boolean DEFAULT true,
    is_gift_box_controlled boolean DEFAULT false,
    remark character varying(50),
    cost_price numeric(18,2),
    location character varying(50),
    is_gift_controlled boolean,
    external_code character varying(50) DEFAULT ''::character varying,
    ydb_zt boolean,
    hg_zt boolean DEFAULT false,
    is_walnut_milk boolean DEFAULT false,
    tax_rate_text character varying(20) DEFAULT '16%'::character varying,
    tax_rate_value numeric(18,2) DEFAULT 0.16,
    distributor_price numeric(18,2),
    xguid character varying(100),
    product_category character varying(50),
    warehouse_id integer,
    virtual_stock numeric(18,2) DEFAULT 0.0,
    stock_quantity numeric(18,2) DEFAULT 0.0
);


--
-- Name: TABLE t_erp_item; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.t_erp_item IS '商品资料表';


--
-- Name: COLUMN t_erp_item.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.id IS '主键ID（自增）';


--
-- Name: COLUMN t_erp_item.row_guid; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.row_guid IS '行唯一标识';


--
-- Name: COLUMN t_erp_item.item_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.item_code IS '商品编码';


--
-- Name: COLUMN t_erp_item.item_full_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.item_full_name IS '商品全称';


--
-- Name: COLUMN t_erp_item.item_short_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.item_short_name IS '商品简称';


--
-- Name: COLUMN t_erp_item.item_pinyin_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.item_pinyin_code IS '商品拼音码';


--
-- Name: COLUMN t_erp_item.item_spec; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.item_spec IS '商品规格';


--
-- Name: COLUMN t_erp_item.category_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.category_id IS '商品分类ID';


--
-- Name: COLUMN t_erp_item.category_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.category_code IS '商品分类代码';


--
-- Name: COLUMN t_erp_item.barcode; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.barcode IS '条形码';


--
-- Name: COLUMN t_erp_item.attr1; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.attr1 IS '属性';


--
-- Name: COLUMN t_erp_item.attr2; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.attr2 IS '属性2';


--
-- Name: COLUMN t_erp_item.package_unit; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.package_unit IS '包装单位';


--
-- Name: COLUMN t_erp_item.package_rate; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.package_rate IS '包装率';


--
-- Name: COLUMN t_erp_item.base_unit; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.base_unit IS '基本单位';


--
-- Name: COLUMN t_erp_item.net_content; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.net_content IS '净含量';


--
-- Name: COLUMN t_erp_item.total_weight; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.total_weight IS '总重量';


--
-- Name: COLUMN t_erp_item.retail_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.retail_price IS '零售单价';


--
-- Name: COLUMN t_erp_item.factory_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.factory_price IS '出厂单价';


--
-- Name: COLUMN t_erp_item.franchise_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.franchise_price IS '加盟单价';


--
-- Name: COLUMN t_erp_item.is_stock_controlled; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.is_stock_controlled IS '库存控制';


--
-- Name: COLUMN t_erp_item.is_enabled; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.is_enabled IS '启用(1=启用)';


--
-- Name: COLUMN t_erp_item.is_combo; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.is_combo IS '组合商品';


--
-- Name: COLUMN t_erp_item.is_publish_controlled; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.is_publish_controlled IS '发布控制';


--
-- Name: COLUMN t_erp_item.is_gift_box_controlled; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.is_gift_box_controlled IS '礼盒控制';


--
-- Name: COLUMN t_erp_item.remark; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.remark IS '备注';


--
-- Name: COLUMN t_erp_item.cost_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.cost_price IS '成本单价';


--
-- Name: COLUMN t_erp_item.location; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.location IS '产品货位';


--
-- Name: COLUMN t_erp_item.is_gift_controlled; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.is_gift_controlled IS '赠品控制';


--
-- Name: COLUMN t_erp_item.external_code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.external_code IS '外部编码';


--
-- Name: COLUMN t_erp_item.ydb_zt; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.ydb_zt IS '（原拼音字段 ydb_zt，语义待确认）';


--
-- Name: COLUMN t_erp_item.hg_zt; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.hg_zt IS '（原拼音字段 hg_zt，语义待确认）';


--
-- Name: COLUMN t_erp_item.is_walnut_milk; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.is_walnut_milk IS '核桃乳商品';


--
-- Name: COLUMN t_erp_item.tax_rate_text; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.tax_rate_text IS '税率(字符串)';


--
-- Name: COLUMN t_erp_item.tax_rate_value; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.tax_rate_value IS '税率数值';


--
-- Name: COLUMN t_erp_item.distributor_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.distributor_price IS '经销价';


--
-- Name: COLUMN t_erp_item.xguid; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.xguid IS '外部同步GUID（原拼音字段 xguid，语义待确认）';


--
-- Name: COLUMN t_erp_item.product_category; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.product_category IS '产品类别';


--
-- Name: COLUMN t_erp_item.warehouse_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.warehouse_id IS '仓库ID';


--
-- Name: COLUMN t_erp_item.virtual_stock; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.virtual_stock IS '虚拟库存';


--
-- Name: COLUMN t_erp_item.stock_quantity; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_item.stock_quantity IS '库存数量';


--
-- Name: t_erp_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_erp_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_erp_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_erp_itemclass; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_erp_itemclass (
    id integer NOT NULL,
    parent_class_code character varying(50),
    class_name character varying(50),
    full_name character varying(250),
    full_code character varying(50),
    class_level integer,
    use_status integer DEFAULT 1,
    top_class_name character varying(50),
    f_parent_id integer
);


--
-- Name: t_erp_itemclass_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_erp_itemclass ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_erp_itemclass_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_erp_itemgroup; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_erp_itemgroup (
    id integer NOT NULL,
    component_item_guid character varying(50),
    component_item_code character varying(30),
    combo_item_guid character varying(50),
    combo_item_code character varying(30),
    base_quantity integer,
    department_id integer,
    is_repair_status boolean DEFAULT false,
    unit_price numeric(18,2)
);


--
-- Name: COLUMN t_erp_itemgroup.unit_price; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_itemgroup.unit_price IS '子商品单价，默认取子商品零售价';


--
-- Name: t_erp_itemgroup_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_erp_itemgroup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_erp_itemgroup_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_erp_menu; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_erp_menu (
    id integer NOT NULL,
    menu_name character varying(500) NOT NULL,
    parent_id integer,
    menu_type integer,
    dll_name character varying(500),
    class_name character varying(500),
    open_type integer,
    flag boolean DEFAULT true NOT NULL,
    memo character varying(500),
    operating integer DEFAULT 0,
    route character varying(64)
);


--
-- Name: COLUMN t_erp_menu.flag; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_menu.flag IS '是否显示';


--
-- Name: COLUMN t_erp_menu.operating; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_menu.operating IS '菜单排序';


--
-- Name: COLUMN t_erp_menu.route; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_menu.route IS 'Web 路由（如 /PmsItem）：菜单与控制器权限绑定的唯一真相源，取代代码内 WebRoutes 字典';


--
-- Name: t_erp_menu_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_erp_menu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_erp_menu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_erp_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_erp_role (
    id integer NOT NULL,
    role_name character varying(100) NOT NULL,
    role_memo text,
    iselect smallint NOT NULL,
    is_readonly smallint DEFAULT 0 NOT NULL
);


--
-- Name: COLUMN t_erp_role.is_readonly; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_erp_role.is_readonly IS '是否只读角色(仅查询,不能有增删改审等操作权限)';


--
-- Name: t_erp_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_erp_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_erp_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_erp_role_menu; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_erp_role_menu (
    id integer NOT NULL,
    role_id integer NOT NULL,
    menu_id character varying(2000)
);


--
-- Name: t_erp_role_menu_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_erp_role_menu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_erp_role_menu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_erp_shop_info; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_erp_shop_info (
    id integer NOT NULL,
    shop_number integer,
    shop_name character varying(100),
    phone character varying(20),
    qq character varying(20),
    address character varying(200),
    order_count integer,
    shop_type character varying(50),
    appkey character varying(100),
    app_secret character varying(100),
    session_key character varying(100),
    session_end_date timestamp(6) with time zone,
    is_auto_down boolean,
    config_data character varying(4000),
    is_message boolean DEFAULT false,
    message character varying(500),
    is_merge boolean DEFAULT false,
    send_aisle character varying(20),
    is_rfm boolean DEFAULT false,
    is_import boolean DEFAULT false,
    shop_sort integer,
    is_hand_merge boolean DEFAULT false,
    is_enable boolean DEFAULT true,
    is_agent boolean DEFAULT false
);


--
-- Name: t_erp_shop_info_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_erp_shop_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_erp_shop_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_erp_user_info; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_erp_user_info (
    id integer NOT NULL,
    account text NOT NULL,
    password text NOT NULL,
    user_name text NOT NULL,
    dep_id integer NOT NULL,
    depot text NOT NULL,
    role_id integer NOT NULL,
    status smallint NOT NULL,
    shop text,
    is_login smallint,
    mac_address character varying(200),
    pwd_must_change boolean NOT NULL
);


--
-- Name: t_pms_batch_no_stock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_pms_batch_no_stock (
    f_inter_id integer NOT NULL,
    f_item_id integer,
    f_batch_num numeric(18,5),
    f_batch_no character varying(50),
    f_bill_type integer,
    f_price numeric(18,5),
    f_beg_date timestamp(6) with time zone,
    f_end_date timestamp(6) with time zone,
    f_state boolean DEFAULT false,
    f_name character varying(50)
);


--
-- Name: t_pms_bill_use; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_pms_bill_use (
    f_inter_id integer NOT NULL,
    f_bill_no character varying(30),
    f_bill_type character varying(10),
    f_date timestamp(6) with time zone,
    f_dept_id integer,
    f_creater_id integer,
    f_remark character varying(1000),
    f_work_shop_id integer,
    f_worker_id integer,
    f_group_id integer,
    f_work_people character varying(1000)
);


--
-- Name: t_pms_bill_use_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_pms_bill_use_entry (
    f_entry_id integer NOT NULL,
    f_inter_id integer NOT NULL,
    f_step_id integer NOT NULL,
    f_bom_id integer NOT NULL,
    f_use_num numeric(18,5),
    f_produce_no character varying(30),
    f_produce_id integer,
    f_item_id integer,
    f_current_use_num numeric(18,5) DEFAULT 0.0,
    f_last_use_num numeric(18,5) DEFAULT 0.0,
    f_schedule_no character varying(30),
    f_schedule_no_id integer,
    f_is_product boolean DEFAULT false,
    f_is_use boolean DEFAULT false
);


--
-- Name: t_pms_bill_use_entry_f_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_pms_bill_use_entry ALTER COLUMN f_entry_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_pms_bill_use_entry_f_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_pms_default_picker_info; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_pms_default_picker_info (
    id integer NOT NULL,
    f_bom_id integer,
    f_dept_id integer,
    f_work_shop_id integer,
    f_group_id integer,
    f_worker_id integer
);


--
-- Name: t_pms_default_picker_info_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_pms_default_picker_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_pms_default_picker_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_pms_goods_apply; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_pms_goods_apply (
    f_inter_id integer NOT NULL,
    f_bill_no character varying(255) NOT NULL,
    f_tran_type smallint,
    f_date timestamp(6) with time zone,
    f_stock_id integer,
    f_emp_id integer,
    f_checker_id integer,
    f_biller_id integer,
    f_dept_id integer,
    f_status smallint NOT NULL,
    f_cancellation boolean NOT NULL,
    f_check_date timestamp(6) with time zone,
    f_explanation character varying(255) DEFAULT ''::character varying NOT NULL,
    f_fetch_add character varying(255) DEFAULT ''::character varying NOT NULL,
    f_work_shop_id integer,
    f_modifyer_id integer,
    f_modify_date timestamp(6) with time zone,
    f_user_id integer
);


--
-- Name: t_pms_goods_apply_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_pms_goods_apply_entry (
    f_entry_id integer NOT NULL,
    f_inter_id integer NOT NULL,
    f_item_id integer,
    f_qty numeric(18,5) DEFAULT 0.0,
    f_price numeric(18,5) DEFAULT 0.0,
    f_amount numeric(18,5) DEFAULT 0.0,
    f_note character(255),
    f_unit_id integer,
    f_fetch_date timestamp(6) with time zone,
    f_sec_coefficient numeric(18,5),
    f_sec_qty numeric(18,5),
    f_stock_id integer,
    f_bom_id integer NOT NULL,
    f_status smallint DEFAULT 0,
    f_fetch_num numeric(18,5) DEFAULT 0.0
);


--
-- Name: COLUMN t_pms_goods_apply_entry.f_status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_pms_goods_apply_entry.f_status IS '0 未导入  1  部分导入 2 已导入';


--
-- Name: COLUMN t_pms_goods_apply_entry.f_fetch_num; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.t_pms_goods_apply_entry.f_fetch_num IS '完成数量';


--
-- Name: t_pms_goods_apply_entry_f_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_pms_goods_apply_entry ALTER COLUMN f_entry_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_pms_goods_apply_entry_f_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_pms_produce_order; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_pms_produce_order (
    f_inter_id integer NOT NULL,
    f_bill_no character varying(30),
    f_date timestamp(6) with time zone,
    f_dept_id integer,
    f_creater_id integer,
    f_applyer_id integer,
    f_apply_no character varying(30),
    f_apply_date timestamp(6) with time zone,
    f_comment character varying(1000),
    f_status smallint NOT NULL,
    f_auditor_id integer,
    f_audit_date timestamp(6) with time zone,
    f_modifyer_id integer,
    f_modify_date timestamp(6) with time zone,
    f_remark character varying(1000),
    f_schedule_no character varying(30),
    f_pick_no character varying(30),
    f_order_status smallint DEFAULT 0,
    f_work_shop_id integer,
    f_schedule_no_id integer
);


--
-- Name: t_pms_produce_order_product_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_pms_produce_order_product_entry (
    f_entry_id integer NOT NULL,
    f_inter_id integer NOT NULL,
    f_plan_num numeric(18,5) DEFAULT 0.0,
    f_plan_date timestamp(6) with time zone NOT NULL,
    f_bom_id integer NOT NULL,
    f_batch_number character varying(100),
    f_produce_type character varying(100) DEFAULT '自制'::character varying,
    f_out_factory character varying(100),
    f_out_price numeric(19,4),
    f_out_amount numeric(19,4),
    f_item_id integer,
    f_picking_status smallint DEFAULT 0,
    f_production_picking_status smallint DEFAULT 0,
    f_stock_status smallint DEFAULT 0,
    f_bill_use_f_inter_id integer,
    f_bill_apply_entry_id integer,
    f_bill_apply_inter_id integer
);


--
-- Name: t_pms_produce_order_product_entry_f_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_pms_produce_order_product_entry ALTER COLUMN f_entry_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_pms_produce_order_product_entry_f_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_pms_produce_order_raw_material_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_pms_produce_order_raw_material_entry (
    f_entry_id integer NOT NULL,
    f_inter_id integer NOT NULL,
    f_step_id integer,
    f_num numeric(18,5),
    f_work_hour_unit character varying(20),
    f_price_unit character varying(20),
    f_fixed_loss numeric(18,5),
    f_loss_stand_value numeric(18,5),
    f_loss_rate character varying(10),
    f_loss_value numeric(18,5),
    f_loss_unit character varying(20),
    f_need_num numeric(18,5),
    f_bom_id integer,
    f_remark character varying(100),
    f_item_id integer
);


--
-- Name: t_pms_produce_order_raw_material_entry_f_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_pms_produce_order_raw_material_entry ALTER COLUMN f_entry_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_pms_produce_order_raw_material_entry_f_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_pms_produce_order_step_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_pms_produce_order_step_entry (
    f_entry_id integer NOT NULL,
    f_inter_id integer NOT NULL,
    f_step_id integer,
    f_algo character varying(20),
    f_hour numeric(18,5),
    f_num numeric(18,5),
    f_single_arti numeric(18,5),
    f_hour_arti numeric(18,5),
    f_price numeric(19,4),
    f_work_hour_unit character varying(20),
    f_price_unit character varying(20),
    f_fixed_loss numeric(18,5),
    f_loss_stand_value numeric(18,5),
    f_loss_rate character varying(10),
    f_loss_value numeric(18,5),
    f_loss_unit character varying(20),
    f_out_put_num numeric(18,5),
    f_plan_out_put_num numeric(18,5),
    f_bom_id integer,
    f_item_id integer
);


--
-- Name: t_pms_produce_order_step_entry_f_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_pms_produce_order_step_entry ALTER COLUMN f_entry_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_pms_produce_order_step_entry_f_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_pms_step; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_pms_step (
    f_item_id integer NOT NULL,
    f_name character varying(255),
    f_type character varying(20),
    f_algo character varying(20),
    f_hour numeric(18,5),
    f_num numeric(18,5),
    f_single_arti numeric(18,5),
    f_hour_arti numeric(18,5),
    f_price numeric(18,5),
    f_work_hour_unit character varying(20),
    f_price_unit character varying(20),
    f_fixed_loss numeric(18,5),
    f_loss_stand_value numeric(18,5),
    f_loss_rate character varying(10),
    f_loss_value numeric(18,5),
    f_loss_unit character varying(20),
    f_delete integer DEFAULT 0
);


--
-- Name: t_pms_step_f_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_pms_step ALTER COLUMN f_item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_pms_step_f_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_pms_step_product_bom; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_pms_step_product_bom (
    id integer NOT NULL,
    fp_item_id integer,
    f_step_id integer,
    f_loss_stand_value numeric(18,5),
    f_loss_rate character varying(10),
    f_loss_value numeric(18,5),
    f_loss_unit character varying(20),
    f_base_num numeric(18,5),
    f_base_unit character varying(20),
    f_cost_type character varying(20),
    f_bom_id integer,
    f_pre_step_id integer,
    f_pre_p_item_id integer,
    f_step_name character varying(50),
    f_remark character varying(1000),
    f_delete integer DEFAULT 0,
    f_is_product boolean DEFAULT false
);


--
-- Name: t_pms_step_product_bom_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_pms_step_product_bom ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_pms_step_product_bom_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_pms_stock_bill; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_pms_stock_bill (
    f_inter_id integer NOT NULL,
    f_bill_no character varying(30),
    f_bill_type integer,
    f_date timestamp(6) with time zone,
    f_dept_id integer,
    f_creater_id integer,
    f_remark character varying(1000),
    f_work_shop_id integer,
    f_manager_id integer,
    f_modify_id integer,
    f_modify_time timestamp(6) with time zone,
    f_bill_type_ex character varying(30),
    f_buying_unit character varying(50),
    f_buyer_id integer,
    f_group_id integer,
    f_inspectors character varying(1000),
    frob smallint DEFAULT 1,
    f_state boolean,
    oaid character varying(255),
    f_source_inter_id integer
);


--
-- Name: t_pms_stock_bill_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_pms_stock_bill_entry (
    f_entry_id integer NOT NULL,
    f_inter_id integer NOT NULL,
    f_step_id integer NOT NULL,
    f_bom_id integer NOT NULL,
    f_produce_no character varying(30),
    f_produce_id integer,
    f_item_id integer,
    f_plan_date timestamp(6) with time zone,
    f_plan_num numeric(18,5),
    f_num numeric(18,5),
    f_price numeric(18,5),
    f_amount numeric(18,5),
    f_num_ext1 numeric(18,5) DEFAULT 0.0,
    f_num_ext2 numeric(18,5) DEFAULT 0.0,
    f_num_ext3 numeric(18,5) DEFAULT 0.0,
    f_schedule_no character varying(30),
    fse_out_no character varying(30),
    f_bill_use_no character varying(30),
    f_buying_no character varying(30),
    f_note character varying(1000),
    f_batch_no character varying(30),
    f_tax_rate character varying(30),
    f_tax_rate_value numeric(18,5),
    f_after_tax_price numeric(18,5),
    f_after_tax_amount numeric(18,5),
    f_tax_amount numeric(18,5),
    f_bom_id_batch_no text,
    f_bill_use_entry_id integer DEFAULT 0,
    f_schedule_no_id integer,
    f_beg_date timestamp(6) with time zone,
    f_end_date timestamp(6) with time zone,
    f_batch_no_id integer,
    frob smallint DEFAULT 1 NOT NULL,
    f_pick_bill_id integer,
    f_pick_entry_id integer
);


--
-- Name: t_pms_stock_bill_entry_f_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_pms_stock_bill_entry ALTER COLUMN f_entry_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_pms_stock_bill_entry_f_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_pms_worker; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_pms_worker (
    id integer NOT NULL,
    f_name text NOT NULL,
    dep_id integer NOT NULL,
    status boolean,
    f_mobile character varying(50),
    fid_number character varying(100)
);


--
-- Name: t_pms_worker_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_pms_worker ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_pms_worker_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: t_erp_data_dict PK__t_ERP_Da__3214EC273F865F66; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_erp_data_dict
    ADD CONSTRAINT "PK__t_ERP_Da__3214EC273F865F66" PRIMARY KEY (id);


--
-- Name: t_erp_department PK__t_ERP_De__3214EC274356F04A; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_erp_department
    ADD CONSTRAINT "PK__t_ERP_De__3214EC274356F04A" PRIMARY KEY (id);


--
-- Name: t_erp_item PK__t_ERP_IT__3214EC276F357288; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_erp_item
    ADD CONSTRAINT "PK__t_ERP_IT__3214EC276F357288" PRIMARY KEY (id);


--
-- Name: t_erp_itemclass PK__t_ERP_IT__3214EC2773FA27A5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_erp_itemclass
    ADD CONSTRAINT "PK__t_ERP_IT__3214EC2773FA27A5" PRIMARY KEY (id);


--
-- Name: t_erp_itemgroup PK__t_ERP_IT__3214EC2777CAB889; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_erp_itemgroup
    ADD CONSTRAINT "PK__t_ERP_IT__3214EC2777CAB889" PRIMARY KEY (id);


--
-- Name: t_erp_menu PK__t_ERP_Me__3214EC273C74E891; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_erp_menu
    ADD CONSTRAINT "PK__t_ERP_Me__3214EC273C74E891" PRIMARY KEY (id);


--
-- Name: t_erp_role PK__t_ERP_Ro__3214EC2710615C29; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_erp_role
    ADD CONSTRAINT "PK__t_ERP_Ro__3214EC2710615C29" PRIMARY KEY (id);


--
-- Name: t_erp_role_menu PK__t_ERP_Ro__3214EC271431ED0D; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_erp_role_menu
    ADD CONSTRAINT "PK__t_ERP_Ro__3214EC271431ED0D" PRIMARY KEY (id);


--
-- Name: t_erp_shop_info PK__t_ERP_Sh__3214EC271BD30ED5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_erp_shop_info
    ADD CONSTRAINT "PK__t_ERP_Sh__3214EC271BD30ED5" PRIMARY KEY (id);


--
-- Name: t_erp_user_info PK__t_ERP_Us__3214EC272FDA0782; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_erp_user_info
    ADD CONSTRAINT "PK__t_ERP_Us__3214EC272FDA0782" PRIMARY KEY (id);


--
-- Name: t_pms_batch_no_stock PK__t_PMS_Ba__7A7754431C5D1EBA; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pms_batch_no_stock
    ADD CONSTRAINT "PK__t_PMS_Ba__7A7754431C5D1EBA" PRIMARY KEY (f_inter_id);


--
-- Name: t_pms_bill_use_entry PK__t_PMS_Bi__70F191902B9F624A; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pms_bill_use_entry
    ADD CONSTRAINT "PK__t_PMS_Bi__70F191902B9F624A" PRIMARY KEY (f_entry_id);


--
-- Name: t_pms_bill_use PK__t_PMS_Bi__7A77544327CED166; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pms_bill_use
    ADD CONSTRAINT "PK__t_PMS_Bi__7A77544327CED166" PRIMARY KEY (f_inter_id);


--
-- Name: t_pms_default_picker_info PK__t_PMS_De__C1BEA5A22F6FF32E; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pms_default_picker_info
    ADD CONSTRAINT "PK__t_PMS_De__C1BEA5A22F6FF32E" PRIMARY KEY (id);


--
-- Name: t_pms_goods_apply_entry PK__t_PMS_Go__70F19190371114F6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pms_goods_apply_entry
    ADD CONSTRAINT "PK__t_PMS_Go__70F19190371114F6" PRIMARY KEY (f_entry_id);


--
-- Name: t_pms_goods_apply PK__t_PMS_Go__7A77544333408412; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pms_goods_apply
    ADD CONSTRAINT "PK__t_PMS_Go__7A77544333408412" PRIMARY KEY (f_inter_id);


--
-- Name: t_pms_produce_order_product_entry PK__t_PMS_Pr__70F191904282C7A2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pms_produce_order_product_entry
    ADD CONSTRAINT "PK__t_PMS_Pr__70F191904282C7A2" PRIMARY KEY (f_entry_id);


--
-- Name: t_pms_produce_order_raw_material_entry PK__t_PMS_Pr__70F1919046535886; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pms_produce_order_raw_material_entry
    ADD CONSTRAINT "PK__t_PMS_Pr__70F1919046535886" PRIMARY KEY (f_entry_id);


--
-- Name: t_pms_produce_order_step_entry PK__t_PMS_Pr__70F191904A23E96A; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pms_produce_order_step_entry
    ADD CONSTRAINT "PK__t_PMS_Pr__70F191904A23E96A" PRIMARY KEY (f_entry_id);


--
-- Name: t_pms_produce_order PK__t_PMS_Pr__7A7754433EB236BE; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pms_produce_order
    ADD CONSTRAINT "PK__t_PMS_Pr__7A7754433EB236BE" PRIMARY KEY (f_inter_id);


--
-- Name: t_pms_stock_bill_entry PK__t_PMS_St__70F1919068A8708A; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pms_stock_bill_entry
    ADD CONSTRAINT "PK__t_PMS_St__70F1919068A8708A" PRIMARY KEY (f_entry_id);


--
-- Name: t_pms_stock_bill PK__t_PMS_St__7A77544364D7DFA6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pms_stock_bill
    ADD CONSTRAINT "PK__t_PMS_St__7A77544364D7DFA6" PRIMARY KEY (f_inter_id);


--
-- Name: t_pms_step_product_bom PK__t_PMS_St__C1BEA5A261074EC2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pms_step_product_bom
    ADD CONSTRAINT "PK__t_PMS_St__C1BEA5A261074EC2" PRIMARY KEY (id);


--
-- Name: t_pms_step PK__t_PMS_St__E24F47EF5D36BDDE; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pms_step
    ADD CONSTRAINT "PK__t_PMS_St__E24F47EF5D36BDDE" PRIMARY KEY (f_item_id);


--
-- Name: t_pms_worker PK__t_PMS_Wo__3214EC27741A2336; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pms_worker
    ADD CONSTRAINT "PK__t_PMS_Wo__3214EC27741A2336" PRIMARY KEY (id);


--
-- Name: FBillNo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "FBillNo" ON public.t_pms_goods_apply USING btree (f_bill_no);


--
-- Name: FInterID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "FInterID" ON public.t_pms_goods_apply USING btree (f_inter_id);


--
-- Name: IX_SBE_BatchNo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_SBE_BatchNo" ON public.t_pms_stock_bill_entry USING btree (f_batch_no);


--
-- Name: IX_SBE_Item_Batch; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_SBE_Item_Batch" ON public.t_pms_stock_bill_entry USING btree (f_item_id, f_batch_no);


--
-- Name: IX_SB_State_Type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_SB_State_Type" ON public.t_pms_stock_bill USING btree (f_state, f_bill_type);


--
-- Name: idx_BomId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_BomId" ON public.t_pms_default_picker_info USING btree (f_bom_id);


--
-- Name: idx_Date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_Date" ON public.t_pms_produce_order USING btree (f_date);


--
-- Name: idx_FBatchNo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FBatchNo" ON public.t_pms_stock_bill_entry USING btree (f_batch_no);


--
-- Name: idx_FBillNo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FBillNo" ON public.t_pms_produce_order USING btree (f_bill_no);


--
-- Name: idx_FBillUseEntryID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FBillUseEntryID" ON public.t_pms_stock_bill_entry USING btree (f_bill_use_entry_id);


--
-- Name: idx_FBomID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FBomID" ON public.t_pms_step_product_bom USING btree (f_bom_id);


--
-- Name: idx_FBomId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FBomId" ON public.t_pms_bill_use_entry USING btree (f_bom_id);


--
-- Name: idx_FBomId1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FBomId1" ON public.t_pms_goods_apply_entry USING btree (f_bom_id);


--
-- Name: idx_FBomId2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FBomId2" ON public.t_pms_produce_order_product_entry USING btree (f_bom_id);


--
-- Name: idx_FBomId3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FBomId3" ON public.t_pms_produce_order_raw_material_entry USING btree (f_bom_id);


--
-- Name: idx_FBomId4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FBomId4" ON public.t_pms_produce_order_step_entry USING btree (f_bom_id);


--
-- Name: idx_FInterID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FInterID" ON public.t_pms_bill_use_entry USING btree (f_inter_id);


--
-- Name: idx_FInterID1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FInterID1" ON public.t_pms_goods_apply_entry USING btree (f_inter_id);


--
-- Name: idx_FInterID2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FInterID2" ON public.t_pms_produce_order_raw_material_entry USING btree (f_inter_id);


--
-- Name: idx_FInterID3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FInterID3" ON public.t_pms_produce_order_step_entry USING btree (f_inter_id);


--
-- Name: idx_FIsProduct; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FIsProduct" ON public.t_pms_step_product_bom USING btree (f_is_product);


--
-- Name: idx_FIsUse; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FIsUse" ON public.t_pms_bill_use_entry USING btree (f_is_use);


--
-- Name: idx_FItemID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FItemID" ON public.t_pms_bill_use_entry USING btree (f_item_id);


--
-- Name: idx_FItemID1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FItemID1" ON public.t_pms_goods_apply_entry USING btree (f_item_id);


--
-- Name: idx_FItemID2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FItemID2" ON public.t_pms_produce_order_product_entry USING btree (f_item_id);


--
-- Name: idx_FItemID3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FItemID3" ON public.t_pms_produce_order_raw_material_entry USING btree (f_item_id);


--
-- Name: idx_FItemID4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FItemID4" ON public.t_pms_produce_order_step_entry USING btree (f_item_id);


--
-- Name: idx_FOrderStatus; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FOrderStatus" ON public.t_pms_produce_order USING btree (f_order_status);


--
-- Name: idx_FPItemID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FPItemID" ON public.t_pms_step_product_bom USING btree (fp_item_id);


--
-- Name: idx_FPickingStatus; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FPickingStatus" ON public.t_pms_produce_order_product_entry USING btree (f_picking_status);


--
-- Name: idx_FProduceId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FProduceId" ON public.t_pms_bill_use_entry USING btree (f_produce_id);


--
-- Name: idx_FProduceNo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FProduceNo" ON public.t_pms_stock_bill_entry USING btree (f_produce_no);


--
-- Name: idx_FProductionPickingStatus; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FProductionPickingStatus" ON public.t_pms_produce_order_product_entry USING btree (f_production_picking_status);


--
-- Name: idx_FScheduleNo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FScheduleNo" ON public.t_pms_bill_use_entry USING btree (f_schedule_no_id);


--
-- Name: idx_FScheduleNo1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FScheduleNo1" ON public.t_pms_produce_order USING btree (f_schedule_no_id);


--
-- Name: idx_FScheduleNoID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FScheduleNoID" ON public.t_pms_stock_bill_entry USING btree (f_schedule_no_id);


--
-- Name: idx_FStatus; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FStatus" ON public.t_pms_produce_order USING btree (f_status);


--
-- Name: idx_FStepID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FStepID" ON public.t_pms_bill_use_entry USING btree (f_step_id);


--
-- Name: idx_FStepID1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FStepID1" ON public.t_pms_produce_order_raw_material_entry USING btree (f_step_id);


--
-- Name: idx_FStepID2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FStepID2" ON public.t_pms_produce_order_step_entry USING btree (f_step_id);


--
-- Name: idx_FStepId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FStepId" ON public.t_pms_step_product_bom USING btree (f_step_id);


--
-- Name: idx_FStockID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FStockID" ON public.t_pms_goods_apply USING btree (f_stock_id);


--
-- Name: idx_FStockID1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FStockID1" ON public.t_pms_goods_apply_entry USING btree (f_stock_id);


--
-- Name: idx_FStockStatus; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FStockStatus" ON public.t_pms_produce_order_product_entry USING btree (f_stock_status);


--
-- Name: idx_Fdate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_Fdate" ON public.t_pms_goods_apply USING btree (f_date);


--
-- Name: idx_Fid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_Fid" ON public.t_erp_itemclass USING btree (f_parent_id);


--
-- Name: idx_FinterId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_FinterId" ON public.t_pms_produce_order_product_entry USING btree (f_inter_id);


--
-- Name: idx_ParentID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_ParentID" ON public.t_erp_department USING btree (parent_id);


--
-- Name: idx_ParentID1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_ParentID1" ON public.t_erp_menu USING btree (parent_id);


--
-- Name: idx_ProduceId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_ProduceId" ON public.t_pms_stock_bill_entry USING btree (f_produce_id);


--
-- Name: idx_ShopNumber; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_ShopNumber" ON public.t_erp_shop_info USING btree (shop_number);


--
-- Name: idx_WorkShopID; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_WorkShopID" ON public.t_pms_worker USING btree (dep_id);


--
-- Name: idx_billtype; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_billtype ON public.t_pms_stock_bill USING btree (f_bill_type);


--
-- Name: idx_class_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_class_name ON public.t_erp_itemclass USING btree (class_name);


--
-- Name: idx_classname; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_classname ON public.t_erp_menu USING btree (class_name);


--
-- Name: idx_combo_item_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_combo_item_code ON public.t_erp_itemgroup USING btree (combo_item_code);


--
-- Name: idx_component_item_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_component_item_code ON public.t_erp_itemgroup USING btree (component_item_code);


--
-- Name: idx_component_item_guid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_component_item_guid ON public.t_erp_itemgroup USING btree (component_item_guid);


--
-- Name: idx_cpgg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cpgg ON public.t_erp_item USING btree (item_spec);


--
-- Name: idx_cpjc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cpjc ON public.t_erp_item USING btree (item_short_name);


--
-- Name: idx_fdate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fdate ON public.t_pms_stock_bill USING btree (f_date);


--
-- Name: idx_guid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_guid ON public.t_erp_item USING btree (row_guid);


--
-- Name: idx_instock_billno; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_instock_billno ON public.t_pms_bill_use USING btree (f_bill_no);


--
-- Name: idx_instock_billno1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_instock_billno1 ON public.t_pms_stock_bill USING btree (f_bill_no);


--
-- Name: idx_instock_fbomid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_instock_fbomid ON public.t_pms_stock_bill_entry USING btree (f_bom_id);


--
-- Name: idx_instock_fdate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_instock_fdate ON public.t_pms_bill_use USING btree (f_date);


--
-- Name: idx_instock_finterid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_instock_finterid ON public.t_pms_stock_bill_entry USING btree (f_inter_id);


--
-- Name: idx_instock_fitemid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_instock_fitemid ON public.t_pms_stock_bill_entry USING btree (f_item_id);


--
-- Name: idx_menutype; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_menutype ON public.t_erp_menu USING btree (menu_type);


--
-- Name: idx_opentype; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_opentype ON public.t_erp_menu USING btree (open_type);


--
-- Name: idx_parent_class_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_parent_class_code ON public.t_erp_itemclass USING btree (parent_class_code);


--
-- Name: idx_processname; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_processname ON public.t_pms_step USING btree (f_name);


--
-- Name: idx_repair_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_repair_status ON public.t_erp_itemgroup USING btree (is_repair_status);


--
-- Name: idx_txm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_txm ON public.t_erp_item USING btree (barcode);


--
-- Name: idx_xcpdm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_xcpdm ON public.t_erp_item USING btree (product_category);


--
-- PostgreSQL database dump complete
--


